ALTER TABLE public.page_revisions 
ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'draft',
ADD COLUMN IF NOT EXISTS revision_number INTEGER,
ADD COLUMN IF NOT EXISTS is_current BOOLEAN DEFAULT FALSE; 