
-- Drop existing foreign key constraints on messages table that reference auth.users
-- These names (messages_sender_id_fkey, messages_receiver_id_fkey) are typically auto-generated by Supabase.
-- If they were named differently in your project, this might need adjustment.
ALTER TABLE public.messages
  DROP CONSTRAINT IF EXISTS messages_sender_id_fkey,
  DROP CONSTRAINT IF EXISTS messages_receiver_id_fkey;

-- Add new foreign key constraints to reference public.profiles(id)
ALTER TABLE public.messages
  ADD CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.profiles(id) ON DELETE CASCADE,
  ADD CONSTRAINT messages_receiver_id_fkey FOREIGN KEY (receiver_id) REFERENCES public.profiles(id) ON DELETE CASCADE;
